name: Build Thwaites

on:
  # Push to master or PR
  push:
    branches:
      - master
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Scheduled build at 0230 UTC on Monday mornings to detect bitrot.
    - cron:  '30 2 * * 1'

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - run: sudo chown -R 1000:1000 /home/runner/work/*

  build:
    needs: clean
    name: "Build Thwaites"  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # The docker container to use.
    container:
      image: firedrakeproject/firedrake-vanilla:latest
    steps:
      - run: ls -ld  /__w/*
      - run: chown -R firedrake:firedrake /_w/*
      - uses: actions/checkout@v2 /_w/thwaites
      - name: Cleanup
        if: ${{ always() }}
        run: |
          cd ..
          rm -rf build
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Thwaites
        run: |
          . /home/firedrake/firedrake/bin/activate
          whoami
          id -u
          id -g
          ls -l
          #python -m pip install -r requirements.txt
          python -m pip install -e .
      - name: Test Thwaites
        run: |
          . /home/firedrake/firedrake/bin/activate
          python $(which firedrake-clean)
          python -m pytest -n 2 -v tests/regression
      - name: Test Thwaites adjoint
        run: |
          . /home/firedrake/firedrake/bin/activate
          python $(which firedrake-clean)
          python -m pytest -n 2 -v tests/adjoint/
      - name: Lint
        if: ${{ always() }}
        run: |
          . /home/firedrake/firedrake/bin/activate
          make lint
