name: Build Thwaites

on:
  # Push to master or PR
  push:
    branches:
      - master
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Scheduled build at 0230 UTC on Monday mornings to detect bitrot.
    - cron:  '30 2 * * 1'

jobs:
  build:
    name: "Build Thwaites"  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # The docker container to use.
    container:
      image: firedrakeproject/firedrake-vanilla:latest
    steps:
      - name: chown
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - uses: actions/checkout@v3
      - name: Cleanup
        if: ${{ always() }}
        run: |
          cd ..
          rm -rf build
      - name: ls
        run: ls -ld  /__w/_temp/_runner_file_commands/*
      - name: Install Thwaites
        run: |
          . /home/firedrake/firedrake/bin/activate
          whoami
          id -u
          id -g
          ls -l
          python -m pip install -r requirements.txt
          python -m pip install -e .
      - name: Test Thwaites
        run: |
          . /home/firedrake/firedrake/bin/activate
          python $(which firedrake-clean)
          python -m pytest -n 2 -v tests/regression
      - name: Test Thwaites adjoint
        run: |
          . /home/firedrake/firedrake/bin/activate
          python $(which firedrake-clean)
          python -m pytest -n 1 -v tests/adjoint/
      - name: Lint
        if: ${{ always() }}
        run: |
          . /home/firedrake/firedrake/bin/activate
          make lint
